apiVersion: v1
kind: Pod
metadata:
  name: arena-pod
  #Link to other objects ( e.g client-node-port.yaml service which holds a selector:web)
  labels:
    package: arena
spec:
  containers:
    - name: centos-httpd
      image: centos/httpd
      resources:
        requests:
          memory: "128M"
          cpu: "100m"
      limits:
        memory: "256M"
        #CPU - 1 unit = 1 core
        cpu: "250m"
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
      ports:
        - containerPort: 3000
