apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: arena-acr-aks
  name: azure-load-balancer
spec:
  selector:
    package: arena
  type: LoadBalancer
  #Under the hood -> ports is declared to route traffic to component selected by the 'selector'
  #Describing all of the related ports to be mapped on the target Object(pod selector)
  ports:
    - name: ssh
      port: 22
      protocol: TCP
    - name: kubernetes-dashboard
      port: 8001
      protocol: TCP
    - name: kube-apiserver-azportreq1
      port: 9000
      protocol: TCP
    - name: kube-apiserver-azportreq2
      port: 1194
      protocol: TCP
    - name: httpd
      port: 80
      protocol: TCP
    - name: https
      protocol: TCP
      port: 443
  # Service (TargetPort = containerPort) Deployment
  # port - internal communication port for other pods on the node. (To have the ability to access the app from another pod)
  # targetPort - In relation with EXPOSE(Docker)=targetPort - (specific app) that we want to send traffic to 
  # nodePort - Number or name of the port to access on the pods targeted by the service. - Agent (chrome) port - to have the ability access the app via URL

  #externalIPs:
  # - 210.1.1.1
  # - 210.1.1.2
  # - 210.1.1.3


