apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  #Link to other objects ( e.g client-node-port.yaml service which holds a selector:web)
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000
